// <auto-generated />
using System;
using Berkshire.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Berkshire.Migrations
{
    [DbContext(typeof(BerkshireContext))]
    [Migration("20210808184916_AddActualReasons")]
    partial class AddActualReasons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Berkshire.DAL.Models.BerkshireReasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BerkshireReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(7864),
                            Reason = "Work with colleagues that have integrity, intelligence, and energy",
                            Updated = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(8205)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(8519),
                            Reason = "Continue to be curious about technology and deliver valuable solutions",
                            Updated = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(8522)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(8523),
                            Reason = "Contribute to the financial strength and security of BHHC's customers, partners, and employees",
                            Updated = new DateTime(2021, 8, 8, 18, 49, 16, 270, DateTimeKind.Utc).AddTicks(8524)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
