// <auto-generated />
using System;
using Berkshire.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Berkshire.Migrations
{
    [DbContext(typeof(BerkshireContext))]
    [Migration("20210805184106_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Berkshire.DAL.Models.BerkshireReasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BerkshireReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6170),
                            Reason = "test 1",
                            Updated = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6512)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6825),
                            Reason = "test 1",
                            Updated = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6827)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6829),
                            Reason = "test 1",
                            Updated = new DateTime(2021, 8, 5, 18, 41, 6, 412, DateTimeKind.Utc).AddTicks(6830)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
