// <auto-generated />
using System;
using Berkshire.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Berkshire.Migrations
{
    [DbContext(typeof(BerkshireContext))]
    partial class BerkshireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Berkshire.DAL.Models.BerkshireReasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BerkshireReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(5672),
                            Reason = "First reason",
                            Updated = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6009)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6318),
                            Reason = "Second reason",
                            Updated = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6320)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6322),
                            Reason = "Third reason",
                            Updated = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6323)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6324),
                            Reason = "Invalid Reason",
                            Updated = new DateTime(2021, 8, 6, 12, 36, 52, 675, DateTimeKind.Utc).AddTicks(6325)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
